import {installSectionNavigation} from './assets/section-navigation.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const [benchmarks,prompts]=await Promise.all(['benchmarks.json','prompts.json'].map(x=>fetch(x).then(r=>{if(!r.ok)throw Error(x);return r.json()})));
installSectionNavigation(document.querySelector('main'));
const lottieMotions=[];const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let paused=reduced;
const scenes=$$('[data-nav-section]');let visibleIndex=0;
const obs=new IntersectionObserver(entries=>{for(const e of entries){e.target.classList.toggle('is-visible',e.isIntersecting);if(e.isIntersecting){visibleIndex=scenes.indexOf(e.target);$('#scene-position').textContent=`${String(visibleIndex+1).padStart(2,'0')} / ${scenes.length}`;$('#scene-prev').disabled=visibleIndex===0;$('#scene-next').disabled=visibleIndex===scenes.length-1;}e.target.querySelectorAll('[data-film]').forEach(v=>{if(e.isIntersecting&&!paused)v.play().catch(()=>{});else v.pause()})}},{threshold:.45});scenes.forEach(s=>obs.observe(s));
function motion(){lottieMotions.forEach(({el,anim})=>{if(paused)anim.pause();else if(el.closest('.is-visible'))anim.play()});document.body.classList.toggle('motion-paused',paused);$('#motion-toggle').setAttribute('aria-pressed',paused);$('#motion-toggle').textContent=paused?'Play motion':'Pause motion';$$('[data-film]').forEach(v=>{if(!paused&&v.closest('.is-visible'))v.play().catch(()=>{});else v.pause()})}motion();$('#motion-toggle').onclick=()=>{paused=!paused;motion()};
function goto(i){i=Math.max(0,Math.min(scenes.length-1,i));scenes[i].scrollIntoView({behavior:reduced?'instant':'smooth'});scenes[i].focus({preventScroll:true});history.replaceState(null,'','#'+scenes[i].id)}$('#scene-prev').onclick=()=>goto(visibleIndex-1);$('#scene-next').onclick=()=>goto(visibleIndex+1);
const mix=$('#mix');function updateMix(){const mode=+mix.value;const labels=['DeepSeek plans and builds.','Astra directs. DeepSeek builds.','Astra handles the whole task.'];const strengths=mode===0?[.16,1]:mode===2?[1,.16]:[1,1];['#astra-orb','#seek-orb'].forEach((id,i)=>{$(id).style.setProperty('--strength',strengths[i]);$(id).classList.toggle('inactive',strengths[i]<1)});$('#mix-caption').textContent=labels[mode];mix.setAttribute('aria-valuetext',['DeepSeek alone','DeepAstra: Astra directs, DeepSeek builds','Astra alone'][mode]);$$('[data-mix]').forEach(b=>{b.classList.toggle('chosen',+b.dataset.mix===mode);b.setAttribute('aria-pressed',+b.dataset.mix===mode)});$('.mix-plus').style.opacity=mode===1?1:.2;}mix.oninput=updateMix;$$('[data-mix]').forEach(b=>b.onclick=()=>{mix.value=b.dataset.mix;updateMix()});updateMix();
let bi=0;const names=['DeepSeek V4.1','Astra','Sol','Grok'];function renderBench(){const b=benchmarks[bi];const words=b.title.split(' ');const last=words.pop();$('#bench-title').innerHTML=words.join(' ')+' <em>'+(/^[A-Z]{2}/.test(last)?last:last.toLowerCase())+'.</em>';$('#bench-subtitle').textContent=b.subtitle;$('#bench-metric').textContent=b.metric;$('#bench-position').textContent=`${String(bi+1).padStart(2,'0')} / ${String(benchmarks.length).padStart(2,'0')}`;$('#bench-note').textContent=b.note;$('#bench-source').href=b.source;const sorted=b.values.map((v,i)=>({v,i})).sort((a,c)=>a.v-c.v);const negative=b.min<0;$('#benchmark-bars').classList.toggle('has-negative',negative);$('#benchmark-bars').innerHTML=sorted.map(({v,i},order)=>{const height=negative?Math.abs(v)/2:v/b.max*100;const anchor=negative?50:0;const top=v<0;return `<div class="ranked-model ${order===3?'leader':''} ${i===0?'seek':''}" style="--bar-color:${i===0?'#79b2ff':'#a1a7aa'}"><div class="ranked-column"><div class="ranked-fill" style="height:${height}%;${top?'top':'bottom'}:${anchor}%"><strong class="ranked-value ${top?'below':''}">${v}${b.suffix}</strong>${i<3?`<img class="brand" src="assets/${i===0?'deepseek':'astra'}.svg" alt="">`:'<img class="brand" src="assets/grok.svg" alt="Grok">'}</div></div><span class="ranked-name">${names[i]}</span></div>`}).join('');$$('[data-benchmark]').forEach((d,i)=>{d.classList.toggle('selected',i===bi);d.setAttribute('aria-pressed',i===bi)})}
$('#bench-dots').innerHTML=benchmarks.map((b,i)=>`<button data-benchmark="${i}" aria-label="${b.title}" aria-pressed="false"></button>`).join('');$$('[data-benchmark]').forEach(b=>b.onclick=()=>{bi=+b.dataset.benchmark;renderBench()});$('#bench-next').onclick=()=>{bi=(bi+1)%benchmarks.length;renderBench()};$('#bench-prev').onclick=()=>{bi=(bi+benchmarks.length-1)%benchmarks.length;renderBench()};renderBench();
function selectGroup(button,selector){$$(selector).forEach(b=>{b.classList.toggle('selected',b===button);b.setAttribute('aria-pressed',b===button)})}
$$('[data-design]').forEach(b=>b.onclick=()=>{selectGroup(b,'[data-design]');const astra=b.dataset.design==='astra';const dir=astra?'astra-raw-high-64k':'deepseek-raw-max-64k';$('#design-image').src=`../results/${dir}/desktop.png`;$('#design-open').href=`../results/${dir}/index.html`;$('#design-cost').textContent=astra?'$1.42':'$0.065';$('#design-meta').textContent=astra?'Direct / High / 64K cap':'Direct / Max / 64K cap';$('#design-verdict').textContent=astra?'Jack’s preferred design.':'Jack’s favourite DeepSeek result.'});
$$('[data-flow]').forEach(b=>b.onclick=()=>{selectGroup(b,'[data-flow]');const hybrid=b.dataset.flow==='hybrid';$('#flow-diagram').innerHTML=hybrid?'<div class="flow-node"><img class="brand" src="assets/astra.svg" alt="OpenAI"><span>Astra: scope + brief</span></div><div class="flow-line"></div><div class="flow-node seek"><img class="brand" src="assets/deepseek.svg" alt="DeepSeek"><span>DeepSeek: implement</span></div><div class="flow-line"></div><div class="flow-node"><img class="brand" src="assets/astra.svg" alt="OpenAI"><span>Astra: focused review</span></div>':'<div class="flow-node">YOU<span>The job</span></div><div class="flow-line"></div><div class="flow-node seek"><img class="brand" src="assets/deepseek.svg" alt="DeepSeek"><span>DeepSeek High</span></div><div class="tool-tray"><span>Files</span><span>Shell</span><span>Checks</span></div>';$('#launch-code').textContent=hybrid?'python3 /path/to/DeepAstra/launch.py exec --cwd . --prompt-file task.txt':'python3 /path/to/DeepAstra/launch.py run --cwd .';$('#flow-caption').textContent=hybrid?'Astra launches a separate DeepSeek worker, then reviews its files.':'A DeepSeek session using the Codex CLI harness.'});
$$('[data-price]').forEach(b=>b.onclick=()=>{selectGroup(b,'[data-price]');const p=b.dataset.price==='peak';$('#price-cached').textContent=p?'$0.006':'$0.003';$('#price-input').textContent=p?'$0.30':'$0.15';$('#price-output').textContent=p?'$1.20':'$0.60'});
function updateMath(){const a=+$('#math-mix').value;const cost=a/100*50+(1-a/100)*.6;$('#math-ratio').textContent=(50/cost).toFixed(2)+'×';$('#math-astra').textContent=a+'% Astra';$('#math-seek').textContent=(100-a)+'% DeepSeek';$('#math-astra-bar').style.width=a+'%';$('#math-cost').textContent='$'+cost.toFixed(2)+' versus $50.00'}$('#math-mix').oninput=updateMath;updateMath();
const dialog=$('#prompt-dialog');let lastFocus;const titles={spreadsheet:'Business report',documents:'Long-document analysis','agentic-os':'Agentic OS','design-continuation':'Design continuation'};function renderPrompt(){const task=$('#prompt-task').value,mode=$('#prompt-mode').value;$('#prompt-title').textContent=titles[task];$('#prompt-text').value=prompts.modes[mode]+'\n'+prompts.common+'\n'+prompts.tasks[task];$('#copy-status').textContent=''}function openPrompt(task){lastFocus=document.activeElement;$('#prompt-task').value=task||'spreadsheet';renderPrompt();dialog.showModal()}$('#prompts-open').onclick=()=>openPrompt();$$('[data-prompt]').forEach(b=>b.onclick=()=>openPrompt(b.dataset.prompt));$('#dialog-close').onclick=()=>dialog.close();dialog.onclose=()=>lastFocus?.focus();dialog.onclick=e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}};$('#prompt-task').onchange=renderPrompt;$('#prompt-mode').onchange=renderPrompt;async function copy(s){try{await navigator.clipboard.writeText(s);return true}catch{return false}}$('#copy-prompt').onclick=async()=>{$('#copy-status').textContent=await copy($('#prompt-text').value)?'Copied':'Select the prompt and copy';};$('[data-copy-command]').onclick=async e=>{e.target.textContent=await copy($('#launch-code').textContent)?'Copied':'Select command';setTimeout(()=>e.target.textContent='Copy',1800)};

if(window.lottie){document.querySelectorAll('.lottie-check').forEach(el=>{const anim=lottie.loadAnimation({container:el,renderer:'svg',loop:false,autoplay:false,path:'assets/check-success.json'});lottieMotions.push({el,anim});const watcher=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting&&!paused){if(reduced)anim.goToAndStop(999,true);else anim.goToAndPlay(0,true)}}),{threshold:.5});watcher.observe(el)});}
