import {installSectionNavigation} from './assets/section-navigation.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const [benchmarks,prompts]=await Promise.all(['benchmarks.json','prompts.json'].map(x=>fetch(x).then(r=>{if(!r.ok)throw Error(x);return r.json()})));
installSectionNavigation(document.querySelector('main'));
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let paused=reduced;
const scenes=$$('[data-nav-section]');let visibleIndex=0;
const obs=new IntersectionObserver(entries=>{for(const e of entries){e.target.classList.toggle('is-visible',e.isIntersecting);if(e.isIntersecting){visibleIndex=scenes.indexOf(e.target);$('#scene-position').textContent=`${String(visibleIndex+1).padStart(2,'0')} / ${scenes.length}`;$('#scene-prev').disabled=visibleIndex===0;$('#scene-next').disabled=visibleIndex===scenes.length-1;}e.target.querySelectorAll('[data-film]').forEach(v=>{if(e.isIntersecting&&!paused)v.play().catch(()=>{});else v.pause()})}},{threshold:.45});scenes.forEach(s=>obs.observe(s));
function motion(){document.body.classList.toggle('motion-paused',paused);$('#motion-toggle').setAttribute('aria-pressed',paused);$('#motion-toggle').textContent=paused?'Play motion':'Pause motion';$$('[data-film]').forEach(v=>{if(!paused&&v.closest('.is-visible'))v.play().catch(()=>{});else v.pause()})}motion();$('#motion-toggle').onclick=()=>{paused=!paused;motion()};
function goto(i){i=Math.max(0,Math.min(scenes.length-1,i));scenes[i].scrollIntoView({behavior:reduced?'instant':'smooth'});scenes[i].focus({preventScroll:true});history.replaceState(null,'','#'+scenes[i].id)}$('#scene-prev').onclick=()=>goto(visibleIndex-1);$('#scene-next').onclick=()=>goto(visibleIndex+1);
const mix=$('#mix');function updateMix(){const a=+mix.value/100;$('#astra-orb').style.opacity=.25+.75*Math.min(1,a*2.5);$('#seek-orb').style.opacity=.25+.75*Math.min(1,(1-a)*2.5);$('#astra-orb').style.filter=`saturate(${a})`;$('#seek-orb').style.filter=`saturate(${Math.min(1,(1-a)*2)})`;$('#astra-orb').style.boxShadow=`0 0 ${a*65}px #d5eaff35,inset 0 0 25px #ffffff09`;$('#mix-label').textContent=a===0?'DeepSeek solo':a===1?'Astra solo':a<.25?'A concise brief':a<.6?'Direction + review':'Frequent supervision';$('#mix-caption').textContent=a===0?'DeepSeek plans, builds and checks the work.':a===1?'Astra handles the task throughout.':a<.25?'Astra defines the target. DeepSeek handles the implementation.':a<.6?'Astra scopes the job. DeepSeek executes. Astra reviews.':'Astra stays involved through implementation and reviews.'}mix.oninput=updateMix;updateMix();
let bi=0;const names=['DeepSeek V4.1','Astra','Sol','Grok'];function renderBench(){const b=benchmarks[bi];$('#bench-title').textContent=b.title;$('#bench-subtitle').textContent=b.subtitle;$('#bench-metric').textContent=b.metric;$('#bench-position').textContent=`${String(bi+1).padStart(2,'0')} / ${String(benchmarks.length).padStart(2,'0')}`;$('#bench-note').textContent=b.note;$('#bench-source').href=b.source;$('#benchmark-bars').innerHTML=b.values.map((v,i)=>{const neg=b.min<0;const width=neg?Math.abs(v)/2:v/b.max*100;const left=neg?(v<0?50-width:50):0;return `<div class="benchmark-row ${i===0?'seek':''}"><span class="benchmark-label">${i<3?`<img class="brand" src="assets/${i===0?'deepseek':'astra'}.svg" alt="">`:''}${names[i]}</span><div class="benchmark-track ${neg?'negative':''}"><i class="benchmark-fill" style="left:${left}%;width:${width}%"></i></div><strong>${v}${b.suffix}</strong></div>`}).join('');$$('[data-benchmark]').forEach((d,i)=>{d.classList.toggle('selected',i===bi);d.setAttribute('aria-pressed',i===bi)});}
$('#bench-dots').innerHTML=benchmarks.map((b,i)=>`<button data-benchmark="${i}" aria-label="${b.title}" aria-pressed="false"></button>`).join('');$$('[data-benchmark]').forEach(b=>b.onclick=()=>{bi=+b.dataset.benchmark;renderBench()});$('#bench-next').onclick=()=>{bi=(bi+1)%benchmarks.length;renderBench()};$('#bench-prev').onclick=()=>{bi=(bi+benchmarks.length-1)%benchmarks.length;renderBench()};renderBench();
function selectGroup(button,selector){$$(selector).forEach(b=>{b.classList.toggle('selected',b===button);b.setAttribute('aria-pressed',b===button)})}
$$('[data-design]').forEach(b=>b.onclick=()=>{selectGroup(b,'[data-design]');const astra=b.dataset.design==='astra';const dir=astra?'astra-raw-high-64k':'deepseek-raw-max-64k';$('#design-image').src=`../results/${dir}/desktop.png`;$('#design-open').href=`../results/${dir}/index.html`;$('#design-cost').textContent=astra?'$1.42':'$0.065';$('#design-meta').textContent=astra?'Direct / High / 64K cap':'Direct / Max / 64K cap';$('#design-verdict').textContent=astra?'Jack’s preferred design.':'Jack’s favourite DeepSeek result.'});
$$('[data-flow]').forEach(b=>b.onclick=()=>{selectGroup(b,'[data-flow]');const hybrid=b.dataset.flow==='hybrid';$('#flow-diagram').innerHTML=hybrid?'<div class="flow-node"><img class="brand" src="assets/astra.svg" alt="OpenAI"><span>Astra: scope + brief</span></div><div class="flow-line"></div><div class="flow-node seek"><img class="brand" src="assets/deepseek.svg" alt="DeepSeek"><span>DeepSeek: implement</span></div><div class="flow-line"></div><div class="flow-node"><img class="brand" src="assets/astra.svg" alt="OpenAI"><span>Astra: focused review</span></div>':'<div class="flow-node">YOU<span>The job</span></div><div class="flow-line"></div><div class="flow-node seek"><img class="brand" src="assets/deepseek.svg" alt="DeepSeek"><span>DeepSeek High</span></div><div class="tool-tray"><span>Files</span><span>Shell</span><span>Checks</span></div>';$('#launch-code').textContent=hybrid?'python3 /path/to/DeepAstra/launch.py exec --cwd . --prompt-file task.txt':'python3 /path/to/DeepAstra/launch.py run --cwd .';$('#flow-caption').textContent=hybrid?'Astra launches a separate DeepSeek worker, then reviews its files.':'A DeepSeek session using the Codex CLI harness.'});
$$('[data-price]').forEach(b=>b.onclick=()=>{selectGroup(b,'[data-price]');const p=b.dataset.price==='peak';$('#price-cached').textContent=p?'$0.006':'$0.003';$('#price-input').textContent=p?'$0.30':'$0.15';$('#price-output').textContent=p?'$1.20':'$0.60'});
function updateMath(){const a=+$('#math-mix').value;const cost=a/100*50+(1-a/100)*.6;$('#math-ratio').textContent=(50/cost).toFixed(2)+'×';$('#math-astra').textContent=a+'% Astra';$('#math-seek').textContent=(100-a)+'% DeepSeek';$('#math-astra-bar').style.width=a+'%';$('#math-cost').textContent='$'+cost.toFixed(2)+' versus $50.00'}$('#math-mix').oninput=updateMath;updateMath();
const dialog=$('#prompt-dialog');let lastFocus;const titles={spreadsheet:'Business report',documents:'Long-document analysis','agentic-os':'Agentic OS','design-continuation':'Design continuation'};function renderPrompt(){const task=$('#prompt-task').value,mode=$('#prompt-mode').value;$('#prompt-title').textContent=titles[task];$('#prompt-text').value=prompts.modes[mode]+'\n'+prompts.common+'\n'+prompts.tasks[task];$('#copy-status').textContent=''}function openPrompt(task){lastFocus=document.activeElement;$('#prompt-task').value=task||'spreadsheet';renderPrompt();dialog.showModal()}$('#prompts-open').onclick=()=>openPrompt();$$('[data-prompt]').forEach(b=>b.onclick=()=>openPrompt(b.dataset.prompt));$('#dialog-close').onclick=()=>dialog.close();dialog.onclose=()=>lastFocus?.focus();dialog.onclick=e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}};$('#prompt-task').onchange=renderPrompt;$('#prompt-mode').onchange=renderPrompt;async function copy(s){try{await navigator.clipboard.writeText(s);return true}catch{return false}}$('#copy-prompt').onclick=async()=>{$('#copy-status').textContent=await copy($('#prompt-text').value)?'Copied':'Select the prompt and copy';};$('[data-copy-command]').onclick=async e=>{e.target.textContent=await copy($('#launch-code').textContent)?'Copied':'Select command';setTimeout(()=>e.target.textContent='Copy',1800)};
